/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ledproject2.view;

/**
 *
 * @author Nitro 5
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboardPannel = new javax.swing.JPanel();
        iconLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        dashboardButton = new javax.swing.JButton();
        availableRoomsButton = new javax.swing.JButton();
        customersButton = new javax.swing.JButton();
        profileButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mainDashboardpanel = new javax.swing.JPanel();
        todayBookPanel = new javax.swing.JPanel();
        tickIcon = new javax.swing.JLabel();
        noOfBokingsLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        todayIncomePanel = new javax.swing.JPanel();
        earningsPicLabel = new javax.swing.JLabel();
        amountLabel = new javax.swing.JLabel();
        todaysIncomeLabel = new javax.swing.JLabel();
        totalIncomePanel = new javax.swing.JPanel();
        totalEarningsPic = new javax.swing.JLabel();
        totalAmountLabel = new javax.swing.JLabel();
        totalIncome = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setResizable(false);
        setSize(new java.awt.Dimension(1400, 800));

        dashboardPannel.setBackground(new java.awt.Color(204, 204, 204));

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ledproject2/view/Vector.png"))); // NOI18N

        welcomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        welcomeLabel.setText("Welcome");

        dashboardButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dashboardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ledproject2/view/dashboard_icon.png"))); // NOI18N
        dashboardButton.setText("Dashboard");
        dashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardButtonActionPerformed(evt);
            }
        });

        availableRoomsButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        availableRoomsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ledproject2/view/availableRooms.png"))); // NOI18N
        availableRoomsButton.setText("Available Rooms");

        customersButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        customersButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ledproject2/view/Customers.png"))); // NOI18N
        customersButton.setText("Customers");
        customersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customersButtonActionPerformed(evt);
            }
        });

        profileButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        profileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ledproject2/view/User2.png"))); // NOI18N
        profileButton.setText("Profile");
        profileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dashboardPannelLayout = new javax.swing.GroupLayout(dashboardPannel);
        dashboardPannel.setLayout(dashboardPannelLayout);
        dashboardPannelLayout.setHorizontalGroup(
            dashboardPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPannelLayout.createSequentialGroup()
                .addGroup(dashboardPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardPannelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(iconLabel))
                    .addGroup(dashboardPannelLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(welcomeLabel))
                    .addGroup(dashboardPannelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(dashboardPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(customersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(availableRoomsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(dashboardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(profileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        dashboardPannelLayout.setVerticalGroup(
            dashboardPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPannelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(welcomeLabel)
                .addGap(114, 114, 114)
                .addComponent(dashboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(availableRoomsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(customersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Azure Haven Hotel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        todayBookPanel.setBackground(new java.awt.Color(204, 255, 204));

        tickIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ledproject2/view/Tick2.png"))); // NOI18N

        noOfBokingsLabel.setText("no.of bookings");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Todays Booking");

        javax.swing.GroupLayout todayBookPanelLayout = new javax.swing.GroupLayout(todayBookPanel);
        todayBookPanel.setLayout(todayBookPanelLayout);
        todayBookPanelLayout.setHorizontalGroup(
            todayBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(todayBookPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tickIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(noOfBokingsLabel)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, todayBookPanelLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(29, 29, 29))
        );
        todayBookPanelLayout.setVerticalGroup(
            todayBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(todayBookPanelLayout.createSequentialGroup()
                .addGroup(todayBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(todayBookPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(tickIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(todayBookPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(noOfBokingsLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(29, 29, 29))
        );

        todayIncomePanel.setBackground(new java.awt.Color(204, 255, 204));

        earningsPicLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ledproject2/view/Money.png"))); // NOI18N
        earningsPicLabel.setText("jLabel4");

        amountLabel.setText("amount");

        todaysIncomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        todaysIncomeLabel.setText("Todays Income");

        javax.swing.GroupLayout todayIncomePanelLayout = new javax.swing.GroupLayout(todayIncomePanel);
        todayIncomePanel.setLayout(todayIncomePanelLayout);
        todayIncomePanelLayout.setHorizontalGroup(
            todayIncomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, todayIncomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(earningsPicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(amountLabel)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, todayIncomePanelLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(todaysIncomeLabel)
                .addGap(32, 32, 32))
        );
        todayIncomePanelLayout.setVerticalGroup(
            todayIncomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(todayIncomePanelLayout.createSequentialGroup()
                .addGroup(todayIncomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(todayIncomePanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(amountLabel))
                    .addGroup(todayIncomePanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(earningsPicLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(todaysIncomeLabel)
                .addGap(32, 32, 32))
        );

        totalIncomePanel.setBackground(new java.awt.Color(204, 255, 204));

        totalEarningsPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ledproject2/view/solar_dollar-bold.png"))); // NOI18N

        totalAmountLabel.setText("Total Amount");

        totalIncome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalIncome.setText("Total Income");

        javax.swing.GroupLayout totalIncomePanelLayout = new javax.swing.GroupLayout(totalIncomePanel);
        totalIncomePanel.setLayout(totalIncomePanelLayout);
        totalIncomePanelLayout.setHorizontalGroup(
            totalIncomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalIncomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalEarningsPic)
                .addGap(41, 41, 41)
                .addComponent(totalAmountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, totalIncomePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalIncome)
                .addGap(39, 39, 39))
        );
        totalIncomePanelLayout.setVerticalGroup(
            totalIncomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalIncomePanelLayout.createSequentialGroup()
                .addGroup(totalIncomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(totalIncomePanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(totalEarningsPic))
                    .addGroup(totalIncomePanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(totalAmountLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalIncome)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout mainDashboardpanelLayout = new javax.swing.GroupLayout(mainDashboardpanel);
        mainDashboardpanel.setLayout(mainDashboardpanelLayout);
        mainDashboardpanelLayout.setHorizontalGroup(
            mainDashboardpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainDashboardpanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(todayBookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(todayIncomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(totalIncomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        mainDashboardpanelLayout.setVerticalGroup(
            mainDashboardpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainDashboardpanelLayout.createSequentialGroup()
                .addGroup(mainDashboardpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(totalIncomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainDashboardpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(todayBookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(todayIncomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(dashboardPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainDashboardpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(dashboardPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(mainDashboardpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(239, 239, 239)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customersButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customersButtonActionPerformed

    private void dashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardButtonActionPerformed

    private void profileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileButtonMouseClicked
    this.setVisible(false);
    Profile profile = new Profile();
    profile.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_profileButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel amountLabel;
    public javax.swing.JButton availableRoomsButton;
    public javax.swing.JButton customersButton;
    public javax.swing.JButton dashboardButton;
    public javax.swing.JPanel dashboardPannel;
    public javax.swing.JLabel earningsPicLabel;
    public javax.swing.JLabel iconLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainDashboardpanel;
    public javax.swing.JLabel noOfBokingsLabel;
    public javax.swing.JButton profileButton;
    public javax.swing.JLabel tickIcon;
    public javax.swing.JPanel todayBookPanel;
    public javax.swing.JPanel todayIncomePanel;
    public javax.swing.JLabel todaysIncomeLabel;
    public javax.swing.JLabel totalAmountLabel;
    public javax.swing.JLabel totalEarningsPic;
    public javax.swing.JLabel totalIncome;
    public javax.swing.JPanel totalIncomePanel;
    public javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
