/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ledproject2.view;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;



import javax.swing.JOptionPane;

/**
 *
 * @author Nitro 5
 */
public class RegistrationForm extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationForm
     */
    public RegistrationForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hotelNameRegistration = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        imageRegisterPage = new javax.swing.JLabel();
        logoRegistration = new javax.swing.JLabel();
        labelBelowLogo = new javax.swing.JLabel();
        labelFirstName = new javax.swing.JLabel();
        firstnameEntryRegister = new javax.swing.JTextField();
        lastnameLabel = new javax.swing.JLabel();
        lastnameEntryRegister = new javax.swing.JTextField();
        emailLabelRegister = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        passwordLabelRegister = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        confirmPassLabelRegister = new javax.swing.JLabel();
        confirmPassEntry = new javax.swing.JPasswordField();
        addressLabelRegister = new javax.swing.JLabel();
        addressEntryRegister = new javax.swing.JTextField();
        phoneEntryRegister = new javax.swing.JLabel();
        phoneLabelRegister = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();
        alreadyAccButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1400, 800));
        setPreferredSize(new java.awt.Dimension(1400, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1400, 800));

        hotelNameRegistration.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Ink Free", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Azure Haven Hotel");

        javax.swing.GroupLayout hotelNameRegistrationLayout = new javax.swing.GroupLayout(hotelNameRegistration);
        hotelNameRegistration.setLayout(hotelNameRegistrationLayout);
        hotelNameRegistrationLayout.setHorizontalGroup(
            hotelNameRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hotelNameRegistrationLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        hotelNameRegistrationLayout.setVerticalGroup(
            hotelNameRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hotelNameRegistrationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        imageRegisterPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ledproject2/view/The 8 best hotels in Mexico where the interior design is even better than the weather 1.jpg"))); // NOI18N

        logoRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ledproject2/view/DALL·E 2025-01-30 17.13.12 - A modern and elegant hotel logo for 'Azure Haven Hotel'. The design should incorporate a luxurious and tranquil theme, featuring a stylized wave or cl 1.png"))); // NOI18N
        logoRegistration.setText("jLabel2");

        labelBelowLogo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelBelowLogo.setText("Tell us about yourself!");

        labelFirstName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelFirstName.setText("Firstname");

        firstnameEntryRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstnameEntryRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameEntryRegisterActionPerformed(evt);
            }
        });

        lastnameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lastnameLabel.setText("Lastname");

        emailLabelRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailLabelRegister.setText("Email");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        passwordLabelRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordLabelRegister.setText("Password");

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        confirmPassLabelRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        confirmPassLabelRegister.setText("Confirm Password");

        confirmPassEntry.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        addressLabelRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addressLabelRegister.setText("Home address");

        phoneEntryRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        phoneLabelRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phoneLabelRegister.setText("Mobile Number");

        registerButton.setBackground(new java.awt.Color(51, 102, 255));
        registerButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registerButton.setText("Register");
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
        });
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        alreadyAccButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        alreadyAccButton.setText("Already have an account?Sign in");
        alreadyAccButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alreadyAccButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imageRegisterPage))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(hotelNameRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(labelBelowLogo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressLabelRegister)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelFirstName)
                                        .addComponent(firstnameEntryRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(emailLabelRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lastnameEntryRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lastnameLabel)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(passwordLabelRegister)
                                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(73, 73, 73)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(confirmPassEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(confirmPassLabelRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jTextField2)
                                .addComponent(addressEntryRegister))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(phoneEntryRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(phoneLabelRegister)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alreadyAccButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(logoRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(519, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hotelNameRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(imageRegisterPage, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logoRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelBelowLogo)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelFirstName)
                            .addComponent(lastnameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstnameEntryRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lastnameEntryRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addGap(6, 6, 6)))
                        .addComponent(emailLabelRegister)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordLabelRegister)
                            .addComponent(confirmPassLabelRegister))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmPassEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(addressLabelRegister)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addressEntryRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(phoneLabelRegister)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phoneEntryRegister)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(alreadyAccButton)
                        .addGap(30, 30, 30)
                        .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void alreadyAccButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alreadyAccButtonMouseClicked
        this.setVisible(false);   
        LoginForm login2 = new LoginForm();
        login2.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_alreadyAccButtonMouseClicked

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseClicked
        this.setVisible(false);
        LoginForm login3 = new LoginForm();
        login3.setVisible(true);
    }//GEN-LAST:event_registerButtonMouseClicked

    private void firstnameEntryRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameEntryRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameEntryRegisterActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
                                               
    // Database connection details
    String url = "jdbc:mysql://localhost:3306/led2"; // Change to your database name
    String user = "root"; // Change to your MySQL username
    String password = "pro@5598"; // Change to your MySQL password

    // Get values from form fields
    String firstname = firstnameEntryRegister.getText();
    String lastname = lastnameEntryRegister.getText();
    String email = jTextField2.getText();
    String pass = new String(jPasswordField1.getPassword());
    String confirmPass = new String(confirmPassEntry.getPassword());
    String address = addressEntryRegister.getText();
    String phone = jTextField1.getText();

if (!pass.equals(confirmPass)) {
        JOptionPane.showMessageDialog(this, "Passwords do not match!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
        // Check if any field is empty
    if (firstname.isEmpty() || lastname.isEmpty() || email.isEmpty() || phone.isEmpty() ||
        address.isEmpty() || password.isEmpty() || confirmPass.isEmpty()) {
        
        // Construct a message for empty fields
        StringBuilder errorMessage = new StringBuilder("Please fill in the following fields:\n");
        
        if (firstname.isEmpty()) {
            errorMessage.append("- First Name\n");
        }
        if (lastname.isEmpty()) {
            errorMessage.append("- Last Name\n");
        }
        if (email.isEmpty()) {
            errorMessage.append("- Email\n");
        }
        if (phone.isEmpty()) {
            errorMessage.append("- Phone\n");
        }
        if (address.isEmpty()) {
            errorMessage.append("- Address\n");
        }
        if (password.isEmpty()) {
            errorMessage.append("- Password\n");
        }
        if (confirmPass.isEmpty()) {
            errorMessage.append("- Confirm Password\n");
        }
        // Email validation to check for @gmail.com


        // Show the error message with missing fields
        JOptionPane.showMessageDialog(this, errorMessage.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        return; // Stop the form submission
    }
    
    if (!email.endsWith("@gmail.com")) {
    JOptionPane.showMessageDialog(this, "Email must be a Gmail address!", "Error", JOptionPane.ERROR_MESSAGE);
    return;
    }
    
    if(phone.length()<10){
    JOptionPane.showMessageDialog(this, "Invalid number!", "Error", JOptionPane.ERROR_MESSAGE);
    return;
    }
    if (!phone.matches("\\d+")) {
    JOptionPane.showMessageDialog(this, "Phone number must contain only digits!", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

    // SQL query to insert data
    String query = "INSERT INTO registrationcredentials (Firstname, Lastname, Email, Password, ConfirmPassword, Address, Phone) VALUES (?, ?, ?, ?, ?, ?, ?)";

    try {
        // Establish connection
        Connection conn = DriverManager.getConnection(url, user, password);
        PreparedStatement stmt = conn.prepareStatement(query);
        
        // Set parameters
        stmt.setString(1, firstname);
        stmt.setString(2, lastname);
        stmt.setString(3, email);
        stmt.setString(4, pass);
        stmt.setString(5,confirmPass);
        stmt.setString(6, address);
        stmt.setString(7, phone);

        // Execute update
        int rowsInserted = stmt.executeUpdate();
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Registration Successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
            new LoginForm().setVisible(true); // Redirect to login page
        }

        // Close resources
        stmt.close();
        conn.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
       // TODO add your handling code here:
    }//GEN-LAST:event_registerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField addressEntryRegister;
    public javax.swing.JLabel addressLabelRegister;
    public javax.swing.JToggleButton alreadyAccButton;
    public javax.swing.JPasswordField confirmPassEntry;
    public javax.swing.JLabel confirmPassLabelRegister;
    public javax.swing.JLabel emailLabelRegister;
    public javax.swing.JTextField firstnameEntryRegister;
    public javax.swing.JPanel hotelNameRegistration;
    public javax.swing.JLabel imageRegisterPage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    public javax.swing.JLabel labelBelowLogo;
    public javax.swing.JLabel labelFirstName;
    public javax.swing.JTextField lastnameEntryRegister;
    public javax.swing.JLabel lastnameLabel;
    public javax.swing.JLabel logoRegistration;
    public javax.swing.JLabel passwordLabelRegister;
    public javax.swing.JLabel phoneEntryRegister;
    public javax.swing.JLabel phoneLabelRegister;
    public javax.swing.JButton registerButton;
    // End of variables declaration//GEN-END:variables
}
